# Generated by Django 5.1.3 on 2024-12-13 05:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='delivered_at',
        ),
        migrations.RemoveField(
            model_name='container',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='containerstatus',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='containerstatus',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_login',
        ),
        migrations.AddField(
            model_name='container',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='containers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Ongoing', max_length=255),
        ),
        migrations.AlterField(
            model_name='container',
            name='size',
            field=models.IntegerField(choices=[(10, '10'), (20, '20'), (40, '40')]),
        ),
        migrations.AlterField(
            model_name='container',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_assignments', to='myapp.container'),
        ),
    ]
